Vagrant.configure(2) do |config|
	config.vm.box = "spox/ubuntu-arm"
	config.vm.define "joowparkS" do |control|
		control.vm.hostname = "joowparkS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.synced_folder "./k3s", "/vagrant"
		control.vm.provider "vmware_desktop" do |vb|
			vb.cpus = 1
			vb.gui = true
		end
		config.vm.provision "shell", inline: <<-SHELL
		SHELL
		control.vm.provision "shell", path: "../scripts/Server-Script.sh"
	end
	# config.vm.define "joowparkSW" do |control|
	# 	control.vm.hostname = "joowparkSW"
	# 	control.vm.network "private_network", ip: "192.168.56.111"
	# 	control.vm.synced_folder "./k3s", "/vagrant"
	# 	control.vm.provider "vmware_desktop" do |vb|
	# 		vb.cpus = 1
	# 		vb.gui = true
	# 	end
	# 	config.vm.provision "shell", inline: <<-SHELL
	# 	SHELL
	# 	control.vm.provision "shell", path: "../scripts/Client-Script.sh"
	# end
end